ktor {
    deployment {
        port = 9393
        sslPort = 9443
    }
    security {
        ssl {
            keyStore = build/keystore.jks
            keyAlias = pttlan
            keyStorePassword = password
            privateKeyPassword = password
        }
    }
    application {
        modules = [ com.pttlan.server.ApplicationKt.module ]
    }
}
