ktor {
    deployment {
        sslPort = 9443
    }
    security {
        ssl {
            keyStore = build/keystore.jks
            keyAlias = pttlan
            keyStorePassword = password
            keyStorePassword = ${?PTT_KEYSTORE_PASSWORD}
            privateKeyPassword = password
            privateKeyPassword = ${?PTT_KEYSTORE_PASSWORD}
        }
    }
    application {
        modules = [ com.pttlan.server.ServerModuleKt.module ]
    }
}

ptt {
    adminPassword = ${?PTT_ADMIN_PASSWORD}
    trustProxy = false
    trustProxy = ${?PTT_TRUST_PROXY}
}
